apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
    name: web-app-portfolio
    app: myportfolio
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: LoadBalancer

